# Build stage using Go 1.25
FROM golang:1.25-bookworm AS build

# Install only essential tools (no SQLite development libraries)
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libc-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /go/src/github.com/MyTeleProject2026/Slotopol-server

# Copy only go.mod – go.sum will be regenerated by go mod download
COPY go.mod ./
RUN go mod download

# Copy the rest of the source
COPY . .

# Make build scripts executable
RUN chmod +x ./task/*.sh

# Build the application (CGO disabled, no SQLite, only MySQL)
RUN ./task/build-docker.sh

# Final lightweight image
FROM scratch

# Copy binary and configuration files
COPY --from=build /go/bin/app /go/bin/app
COPY --from=build /go/src/github.com/MyTeleProject2026/Slotopol-server/appdata /appdata

# Expose the default port
EXPOSE 8080

# Run the server
ENTRYPOINT ["/go/bin/app"]
CMD ["-v", "web"]
