services:
  - type: web
    name: slotopol-server
    runtime: go
    repo: https://github.com/MyTeleProject2026/Slotopol-server
    plan: starter
    buildCommand: go build -tags netgo -ldflags "-s -w" -o slotopol-server
    startCommand: ./slotopol-server -v web
    healthCheckPath: /ping
    envVars:
      - key: SLOTOPOL_DBDRIVER
        value: mysql
      - key: SLOTOPOL_CLUBDSN
        sync: false
      - key: SLOTOPOL_SPINDSN
        sync: false
      - key: SLOTOPOL_ACCESS_KEY
        generateValue: true
      - key: SLOTOPOL_REFRESH_KEY
        generateValue: true
      - key: SLOTOPOL_CLOUDINARY_CLOUD_NAME
        sync: false
      - key: SLOTOPOL_CLOUDINARY_API_KEY
        sync: false
      - key: SLOTOPOL_CLOUDINARY_API_SECRET
        sync: false
